### ISSUE TITLE
Debian install crashes

### ISSUE THREAD

**Issue by nagordon** [andrea-cuttone/geoplotlib#1]
```bash
In [1]: import geoplotlib 
libGL error: pci id for fd 10: 80ee:beef, driver (null)
OpenGL Warning: glFlushVertexArrayRangeNV not found in mesa table
OpenGL Warning: glVertexArrayRangeNV not found in mesa table
OpenGL Warning: glCombinerInputNV not found in mesa table
OpenGL Warning: glCombinerOutputNV not found in mesa table
OpenGL Warning: glCombinerParameterfNV not found in mesa table
OpenGL Warning: glCombinerParameterfvNV not found in mesa table
OpenGL Warning: glCombinerParameteriNV not found in mesa table
OpenGL Warning: glCombinerParameterivNV not found in mesa table
OpenGL Warning: glFinalCombinerInputNV not found in mesa table
OpenGL Warning: glGetCombinerInputParameterfvNV not found in mesa table
OpenGL Warning: glGetCombinerInputParameterivNV not found in mesa table
OpenGL Warning: glGetCombinerOutputParameterfvNV not found in mesa table
OpenGL Warning: glGetCombinerOutputParameterivNV not found in mesa table
OpenGL Warning: glGetFinalCombinerInputParameterfvNV not found in mesa table
OpenGL Warning: glGetFinalCombinerInputParameterivNV not found in mesa table
OpenGL Warning: glDeleteFencesNV not found in mesa table
OpenGL Warning: glFinishFenceNV not found in mesa table
OpenGL Warning: glGenFencesNV not found in mesa table
OpenGL Warning: glGetFenceivNV not found in mesa table
OpenGL Warning: glIsFenceNV not found in mesa table
OpenGL Warning: glSetFenceNV not found in mesa table
OpenGL Warning: glTestFenceNV not found in mesa table
libGL error: core dri or dri2 extension not found
libGL error: failed to load driver: vboxvideo
Segmentation fault
```

**Comment by nagordon** [comment]
BTW, I have Anaconda install and installed pyglet via pip

**Comment by andrea-cuttone** [comment]
I have not tried it on debian. 
However to me it looks like an issue with pyglet/opengl. Can you try to run the [pyglet hello world example](http://www.pyglet.org/doc/programming_guide/hello_world.html) and see if it works?

**Comment by arnaldorusso** [comment]
Hi @nagordon
Do you have `libqt4-opengl` installed wide system?
I have installed `geoplotlib` inside my debian directly with no problems, and everything is alright.
Cheers

**Comment by nagordon** [comment]
Also, I am using a VirtualBox and Linux-Mint-Cinnamon

It appears that I do have ```libqt4-opengl``` installed. 

    $ sudo apt-get install libqt4-opengl
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    libqt4-opengl is already the newest version.
    0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

I install the latest pylget vis ```pip install --upgrade https://bitbucket.org/pyglet/pyglet/get/tip.zip ```

    In [1]: import pyglet
    In [2]: window = pyglet.window.Window()
    libGL error: pci id for fd 7: 80ee:beef, driver (null)
    OpenGL Warning: glFlushVertexArrayRangeNV not found in mesa table
    OpenGL Warning: glVertexArrayRangeNV not found in mesa table
    OpenGL Warning: glCombinerInputNV not found in mesa table
    OpenGL Warning: glCombinerOutputNV not found in mesa table
    OpenGL Warning: glCombinerParameterfNV not found in mesa table
    OpenGL Warning: glCombinerParameterfvNV not found in mesa table
    OpenGL Warning: glCombinerParameteriNV not found in mesa table
    OpenGL Warning: glCombinerParameterivNV not found in mesa table
    OpenGL Warning: glFinalCombinerInputNV not found in mesa table
    OpenGL Warning: glGetCombinerInputParameterfvNV not found in mesa table
    OpenGL Warning: glGetCombinerInputParameterivNV not found in mesa table
    OpenGL Warning: glGetCombinerOutputParameterfvNV not found in mesa table
    OpenGL Warning: glGetCombinerOutputParameterivNV not found in mesa table
    OpenGL Warning: glGetFinalCombinerInputParameterfvNV not found in mesa table
    OpenGL Warning: glGetFinalCombinerInputParameterivNV not found in mesa table
    OpenGL Warning: glDeleteFencesNV not found in mesa table
    OpenGL Warning: glFinishFenceNV not found in mesa table
    OpenGL Warning: glGenFencesNV not found in mesa table
    OpenGL Warning: glGetFenceivNV not found in mesa table
    OpenGL Warning: glIsFenceNV not found in mesa table
    OpenGL Warning: glSetFenceNV not found in mesa table
    OpenGL Warning: glTestFenceNV not found in mesa table
    libGL error: core dri or dri2 extension not found
    libGL error: failed to load driver: vboxvideo
    Segmentation fault


looks like a issue with pyglet. I will try it at home on a non-virtualbox machine. Thanks.

**Comment by andrea-cuttone** [comment]
Hi

have you tested this again? Is it still an issue?

**Comment by nagordon** [comment]
I have not done any more testing on debian. but have been using geoplotlib
on windows without issue. Thanks


Neal Gordon

**Comment by andrea-cuttone** [comment]
Closing as no more problems are reported
