### ISSUE TITLE
[geoplotlib.graph] about edge color.

### ISSUE THREAD

**Issue by RiptideBo** [andrea-cuttone/geoplotlib#26]
First of all, really thank **geoplotlib** . It helps me a lot.

I recently use geoplotlib.graph to create graph on map, I notice that the color of edges represents the length of edges(I find it in the paper)。

I wonder if there are any chance to draw the edge color based on edge weights or something else ?

**Comment by andrea-cuttone** [comment]
Happy to hear that you find it helpful : )

The graph edges color is currently hardcoded to use the distance. You can copy the code from the GraphLayer from https://github.com/andrea-cuttone/geoplotlib/blob/master/geoplotlib/layers.py and define your own custom layer with the logic you need.

**Comment by RiptideBo** [comment]
This's really cool. Thank you a lot！
