### ISSUE TITLE
How to turn off tile provider ?

### ISSUE THREAD

**Issue by jackmiemie** [andrea-cuttone/geoplotlib#34]
Hi,
   I'm using geoplotlib for academic research and projects. Sometimes I only want the graph, such as air flight graph, but not map tiles. Is there a way to turn off tile provider and let the graph rendered on a blank background ?

   I have found a solution but it is a little bit inelegant. I set the tile provider with a invalid url so that the background will be black and no map tile will appear. My solution is easy, but every time I shut down the pyglet window, there will be a huge bunch of warnings, which will take some time to wait for my ipython console to display them. Is there a more elegant way ?

   Thank you !

**Comment by RiptideBo** [comment]
What I am doing is quite similar with yours about complex network. (spatially embedded network).
and my solution is:
- use **geojson** to make it json. 
- transform json to **shp**( shapefile )
- open shp file with **arcgis**

in this way you can save as high resolution photo.

or if you dont want it on map, why not use **matplotlib** or **pygraphistry** or just **gephi**.

**Comment by andrea-cuttone** [comment]
you can press M to disable the map drawing
