### ISSUE TITLE
way to store the output as a image

### ISSUE THREAD

**Issue by akanshajainn** [andrea-cuttone/geoplotlib#35]
I know I can use the keyboard key 'P' to take a screenshot, but I want to save the output using python only, since once we execute it runs in GUI in background but there's no way to save the result.

**Comment by andrea-cuttone** [comment]
you can try to use GeoplotlibApp.screenshot(fname)

**Comment by akanshajainn** [comment]
Tried 
1. GeoplotlibApp.screenshot(fname)
2. geoplotlib.screenshot(fname)
Error:
name 'GeoplotlibApp' is not defined
module 'geoplotlib' has no attribute 'screenshot'

**Comment by akanshajainn** [comment]
Okay so I figured out the way to store the output as a image.
1. geoplotlib.savefig('filename without extension default is png'). Check out sample code to work this out.
`import geoplotlib
from geoplotlib.utils import read_csv
data = read_csv('lat_lon.csv')
geoplotlib.dot(data)
geoplotlib.savefig('abc.jpg')`
Please mention the geoplotlib.show() won't work with savefig.

Now for the error mentioned above, the correct code is: `geoplotlib.GeoplotlibApp.screenshot('filename')
`
but still it doesn't work, it outputs an empty image.
