### ISSUE TITLE
problem importing geoplotlib under Windows 7

### ISSUE THREAD

**Issue by sabinej** [andrea-cuttone/geoplotlib#4]
I am running Windows 7 Enterprise (Service Pack 1). I run Python 2.7. I can run the pyglet "hello world" but when I import geoplotlib, I get the following error message:

Traceback (most recent call last):
  File "<pyshell#1>", line 1
    import geoplotlib
  File "C:\Python27\Lib\site-packages\geoplotlib\__init__.py", line 24
    _global_config = AppConfig()
  File "C:\Python27\Lib\site-packages\geoplotlib\__init__.py", line 9, in __init__
    self.reset()
  File "C:\Python27\Lib\site-packages\geoplotlib\__init__.py", line 19, in reset
    screen =  pyglet.canvas.get_display().get_default_screen()
AttributeError: 'module' object has no attribute 'canvas'

I did import pyglet before importing geoplotlib, and it does not make any difference. I also re-installed geoplotlib from the source, as you advised, but it still gives the same message.

Pyglet was already installed with the Python version I downloaded a while ago (Python 2.7 from Enthought)

Many thanks!!

**Comment by sabinej** [comment]
My pyglet version is 1.1.4

**Comment by andrea-cuttone** [comment]
The problem is with pyglet version 1.1.x which has an older API and a number of other issues.

I would ask you to upgrade to the [latest pyglet 1.2.x](http://www.pyglet.org/download.html) and try again

**Comment by sabinej** [comment]
Thanks! It now loads geoplotlib just fine.
