### ISSUE TITLE
Negative values for maps

### ISSUE THREAD

**Issue by sabinej** [andrea-cuttone/geoplotlib#6]
I'd like to show percentage changes of a quantity for different states on a map. However, in color.py, it generates an exception for negative values. When looking at colormap examples for matplotlib  at http://matplotlib.org/examples/color/colormaps_reference.html  it seems that the "diverging" colormaps are made for positive and negative values. Is there a deep reason for this exception, or could I comment it out and re-install geoplotlib like that? Thanks!

**Comment by andrea-cuttone** [comment]
The negative values are not allowed since the colorscale domain (i.e. the allowed values) is assumed to start from 0.
But I understand how this prevents to use diverging colorscales, which are quite useful.

I will try to find a way to fix this.

**Comment by andrea-cuttone** [comment]
Which layer are you trying to use for this visualization? I guess the only layers that could currently support diverging colors are the choropleth (geojson) or a custom layer

**Comment by sabinej** [comment]
You are right, I'm trying to use this for the choropleth maps (showing positive and negative GDP changes for US states).

**Comment by andrea-cuttone** [comment]
I added a minvalue parameter to ColorMap.to_color().
Using an appropriate minvalue and maxvalue you should now be able to map both negative and positive values in a diverging colorscale

**Comment by sabinej** [comment]
Thanks!! It works great.
