### ISSUE TITLE
Cannot import name get_cmap on some examples

### ISSUE THREAD

**Issue by sudheesh001** [andrea-cuttone/geoplotlib#9]
Stacktrace, Is there something that's missing to run this sample, I am facing this issue on
1. delaunay.py
2. graph-flights.py
3. choropleth.py
4. kde.py
5. voronoi-filled.py

```
2015-09-30 12:05:38.429 Python[19294:2380557] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/sx/5cqr_xwj5c50nlc6by1431sm0000gn/T/org.python.python.savedState
Traceback (most recent call last):
  File "delaunay.py", line 10, in <module>
    geoplotlib.delaunay(data, cmap='hot_r')
  File "build/bdist.macosx-10.10-x86_64/egg/geoplotlib/__init__.py", line 177, in delaunay
  File "build/bdist.macosx-10.10-x86_64/egg/geoplotlib/layers.py", line 405, in __init__
  File "build/bdist.macosx-10.10-x86_64/egg/geoplotlib/colors.py", line 18, in __init__
ImportError: cannot import name get_cmap
```

**Comment by andrea-cuttone** [comment]
Hi

is this solved if you install matplotlib?

**Comment by sudheesh001** [comment]
Hi looks like this is resolved. it was a strange issue which seems to appear randomly. I am closing this as of now as it works for me in this case. Sorry for the trouble :+1:

**Comment by andrea-cuttone** [comment]
No worries. Happy to hear you got it to work :)

**Comment by hitpotato** [comment]
@sudheesh001 Hi, I am having ImportError: cannot import name get_cmap too, How did you solve it?

Thanks,

**Comment by andrea-cuttone** [comment]
Hi

as mentioned before, do you have matplotlib installed?

**Comment by hitpotato** [comment]
Yes, I did, and import matplotlib did work in python.

Here is the error message I got(Windows 10, pip installation):
![error](https://cloud.githubusercontent.com/assets/6627352/17094700/c971e8d8-5205-11e6-839d-9011f545b211.png)

**Comment by andrea-cuttone** [comment]
if you run a python console and execute the following:


```
import matplotlib
print matplotlib.__version__
```

what does it show?

and if you run the following:

```
from pylab import get_cmap
```

do you get the same error?

**Comment by hitpotato** [comment]
For the first one, I got:
`1.5.2`
For the sec, I got:
```
Traceback (most recent call last):
   File"<stdin>", line 1, in <module>
ImportError: cannot import name get_camp
```

**Comment by andrea-cuttone** [comment]
I looked at the released versions, and the closest versions in pip are 1.5.1 and 2.0.0b1, but I do not see this 1.5.2. 
I tried the 1.5.1 and then 2.0.0b1 versions, and both work fine since the `get_cmap` method is there.

How did you install matplotlib?

If you do a `pip list`, which version of matplotlib is shown?
